services:

  backend:
    build: src
    ports:
      - "8080:8080"
    depends_on:
      - redis
    links:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
  
  # viewer
  redis-viewer:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=
    ports:
      - 8081:8081
    depends_on:
      - redis

volumes:
  redis-data:  